name: educhain
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_picker: ^1.1.2
  share_plus: ^10.1.2
  intl: ^0.18.0


  flutter_lints: ^3.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo01.png
    - assets/images/logo02.png
    - assets/images/logo03.png
    - assets/images/logo04.png
    - assets/images/logo05.png
    - assets/images/background01.png
    - assets/images/background02.png
    - assets/images/icon/icon01.png
    - assets/images/icon/icon02.png
    - assets/images/icon/icon03.png
    - assets/images/icon/icon04.png
    - assets/images/icon/icon05.png
    - assets/images/icon/icon06.png
    - assets/images/icon/icon07.png
    - assets/images/icon/icon08.png
    - assets/images/icon/icon09.png
    - assets/images/icon/icon10.png
    - assets/images/icon/icon11.png
    - assets/images/icon/icon12.png
    - assets/images/icon/icon13.png
    - assets/images/icon/icon14.png
    - assets/images/icon/icon15.png
    - assets/images/icon/icon16.png
    - assets/images/icon/icon17.png
    - assets/images/icon/icon18.png
    - assets/images/icon/vietnam.png
    - assets/images/icon/google.png
    - assets/images/icon/facebook.png
    - assets/images/icon/metamask.png
    - assets/images/icon/lock.png
    - assets/images/image.png
    - assets/images/image01.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
